import { Poppins,  Roboto_Serif, Parisienne,  } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Poppins({ 
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
 })

 const parisienne = Parisienne({ 
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-parisienne',
 })

 const robotoSerif = Roboto_Serif({
  weight: ['100', '200', '300', '400', '500', '600', '700', ],
  subsets: ['latin'],
  variable: '--font-robotoserif'
 })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${parisienne.variable} ${poppins.variable} ${robotoSerif.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
